num = {1,2,3,4,5,6}
print (num)
num.add(60)
print(num)
max_no = max(1,4,5,3,5)
print( 'max number', max_no)
min_no = min(num)
print('min number', min_no)
l = len(num)
print('length',l)
num.discard(60)
print(num)
x = {'apple','banana','cherry'}
print(x)
y = {'apple','microsoft','google'}
print(y)
z = x.union(y)
print('union',z)
i = x.intersection(y)
print('intersection',i)
d = x.difference(y)
print('difference',d)
s = x.symmetric_difference(y)
print('symmetric_difference',s)
num.clear()
print (num)